# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nuggets of Information
subtitle: From the Quagmire of My Mind
email: pdaugavietis@sdlc.solutions
description: >- # this means to ignore newlines until "baseurl:"
  Just somewhere to dump pearls of wisdom (and sometimes other stuff) from a old, tired nerd
  that's been doing DevOps and related things for FAR to long :)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pdaugavietis.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pdaugavietis
github_username:  pdaugavietis

github:
  is_user_page: true
  owner_url: https://github.com/pdaugavietis

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/archives/:year/'
    month: '/archives/:year/:month/'
    day: '/archives/:year/:month/:day/'
    tag: '/archives/tag/:name/'
    category: '/archives/category/:name/'
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    category: tagcategory-archive
    tag: tagcategory-archive

show_downloads: false

navbar-links:
  # Posts Calendar: "posts-cal"
  # Posts by Tag: "tags"
  About Me: 
    - About: "aboutme"
    - Resume: https://registry.jsonresume.org/pdaugavietis
  Links:
    - Link Log: "linklog"
    - Github: https://github.com/pdaugavietis
    - Docker Hub: https://hub.docker.com/u/pdaugavietis/
    - Travis CI: https://travis-ci.org/pdaugavietis
  Archives: 
    - By Date: "archive"
    - By Tag: "tags"
  Search: "search"

# Build settings
markdown: kramdown
# permalink: /:year-:month-:day-:title/
permalink: /:title/

paginate: 7
excerpt_length: 50

github: [metadata]

# theme: dinky
plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-paginate
  # - jekyll-compose
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-sitemap
  
remote_theme: pdaugavietis/dinky-pages-theme

# theme: minima
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
